name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          wget --progress=dot:giga https://wufs.wustl.edu/SpaceApps/data/space_apps_2024_seismic_detection.zip
          unzip space_apps_2024_seismic_detection
          cd space_apps_2024_seismic_detection
          git config --global init.defaultBranch main
          git config --global user.name "Mohamed Hisham Abdelzaher"
          git config --global user.email "mohamed.hisham.abdelzaher@gmail.com"
          git init
          git remote add origin https://github.com/MH0386/space_apps_2024_seismic_detection.git
          git branch -M main
          git push -u origin main
